### ISSUE TITLE
Implement storenode message counter

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/storenode-messages-counter#8]
Milestone: https://github.com/waku-org/pm/issues/167

- [x] Script to create fake messages in nwaku to test functionality
- [x] Retrieve message history from a list of nodes and pubsub topics
- [X] Compare message history among nodes and list messages not found
- [x] SQLite support
- [x] Postgresql support  
- [x] Dockerfile
- [x] Tests (*in progress*)
- [x] CI setup
- [x] Installation in telemetry server

**Comment by richard-ramos** [comment]
Implemented and deployed

**Comment by fryorcraken** [comment]
Can we have a link to the dashboard please?
