### ISSUE TITLE
Deployment as part of telemetry setup

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/storenode-messages-counter#9]
Hello infra team!

I have created this project so we can have a monitor to determine the difference in message history among a set of storenodes, and would like to deploy it. This program what it does is periodically query via store protocol the message history, and if it identifies a missing message, store it into a table in PostgreSQL

This project must be setup to run with the following settings:

shards.test:
```
storemsgcounter \
  --storenode=/dns4/store-01.do-ams3.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT \
  --storenode=/dns4/store-02.do-ams3.shards.test.status.im/tcp/30303/p2p/16Uiu2HAm9aDJPkhGxc2SFcEACTFdZ91Q5TJjp76qZEhq9iF59x7R \
  --storenode=/dns4/store-01.gc-us-central1-a.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmMELCo218hncCtTvC2Dwbej3rbyHQcR8erXNnKGei7WPZ \
  --storenode=/dns4/store-02.gc-us-central1-a.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmJnVR7ZzFaYvciPVafUXuYGLHPzSUigqAmeNw9nJUVGeM \
  --storenode=/dns4/store-01.ac-cn-hongkong-c.shards.test.status.im/tcp/30303/p2p/16Uiu2HAm2M7xs7cLPc3jamawkEqbr7cUJX11uvY7LxQ6WFUdUKUT \
  --storenode=/dns4/store-02.ac-cn-hongkong-c.shards.test.status.im/tcp/30303/p2p/16Uiu2HAm9CQhsuwPR54q27kNj9iaQVfyRzTGKrhFmr94oD8ujU6P \
  --cluster-id=16 \
  --pubsub-topic=/waku/2/rs/16/1 \
  --pubsub-topic=/waku/2/rs/16/32 \
  --pubsub-topic=/waku/2/rs/16/64 \
  --db-url=postgresql://postgres:your_password@localhost:5432/postgres \
  --retention-policy=360h0m0s
```
(replace the `--db-url` flag with the telemetry DB url,  also, likely on monday I'll add a feature so we can use a dns discovery URL instead of having to specify each node manually)

There's a dockerfile that builds this project included in the root of the repository.

What changes / information would you require to make this project easier to setup and deploy?

**Comment by jakubgs** [comment]
Does it make sense to run this separately from telemetry service, or should we just include it in the compose for it?

https://github.com/status-im/infra-misc/blob/master/ansible/roles/telemetry/templates/docker-compose.yml.j2

**Comment by jakubgs** [comment]
Also, do you expect rapid development on this? As it, does this require a CI job and automatic deployments?

**Comment by richard-ramos** [comment]
> Does it make sense to run this separately from telemetry service, or should we just include it in the compose for it?

I think it can be run as part of telemetry compose, as they will share the same database
(but the tool itself is 'agnostic' in the sense that it can live on its own)

> Also, do you expect rapid development on this? As it, does this require a CI job and automatic deployments?

Yeah, I do expect it to change a bit in the next two weeks, because it's on active development, and even tho I have done some testing, it has not been run in real life so there might be issues hidden!

**Comment by jakubgs** [comment]
Renamed repo to: https://github.com/waku-org/storenode-messages-counter

**Comment by jakubgs** [comment]
Created a CI job: https://ci.infra.status.im/job/telemetry/job/storenode-messages-counter/

Here's the PR for Jekinsfile:

- https://github.com/waku-org/storenode-messages-counter/pull/10

**Comment by jakubgs** [comment]
Also moved `telemetry` repo in Harbor under `wakuorg`:

- https://harbor.status.im/harbor/projects/9/repositories/telemetry/
- https://harbor.status.im/harbor/projects/9/repositories/storenode-messages-counter/

**Comment by richard-ramos** [comment]
Added the following flags:
```
--dns-discovery-url value [ --dns-discovery-url value ]              URL for DNS node list in format 'enrtree://<key>@<fqdn>'. Option may be repeated 
--dns-discovery-name-server value    value  DNS nameserver IP to query (empty to use system's default)
```

**Comment by jakubgs** [comment]
The node fails to start with:
```
panic: no migration found for version 4: read version 4 <go-bindata>: file does not exist
goroutine 1 [running]:
main.main()
#011/go/src/github.com/waku-org/storenode-messages/cmd/storemsgcounter/main.go:30 +0x1ba
```

**Comment by jakubgs** [comment]
If I remove the `--db-url` flag it starts:
```
2024-05-21T07:30:09.247Z#011#033[34mINFO#033[0m#011gowaku#011node/wakunode2.go:921#011attempting DNS discovery with #011{"URL": "enrtree://AMOJVZX4V6EXP7NTJPMAYJYST2QP6AJXYW76IU6VGJS7UVSNDYZG4@boot.test.shards.nodes.status.im"}
2024-05-21T07:30:09.269Z#011#033[34mINFO#033[0m#011gowaku#011node/wakunode2.go:930#011found dns entries #011{"nodes": [{"ID":"16Uiu2HAm8mUZ18tBWPXDQsaF7PbCKYA35z7WB2xNZH2EVq1qS8LJ","Addrs":["/ip4/34.135.13.87/tcp/30303","/dns4/boot-01.gc-us-central1-a.shards.test.status.im/tcp/30303","/dns4/boot-01.gc-us-central1-a.shards.test.status.im/tcp/443/wss"]},{"ID":"16Uiu2HAmGwcE8v7gmJNEWFtZtojYpPMTHy2jBLL6xRk33qgDxFWX","Addrs":["/ip4/8.218.23.76/tcp/30303","/dns4/boot-01.ac-cn-hongkong-c.shards.test.status.im/tcp/30303","/dns4/boot-01.ac-cn-hongkong-c.shards.test.status.im/tcp/443/wss"]},{"ID":"16Uiu2HAmAR24Mbb6VuzoyUiGx42UenDkshENVDj4qnmmbabLvo31","Addrs":["/ip4/167.99.19.47/tcp/30303","/dns4/boot-01.do-ams3.shards.test.status.im/tcp/30303","/dns4/boot-01.do-ams3.shards.test.status.im/tcp/443/wss"]}]}
2024-05-21T07:30:09.277Z#011#033[34mINFO#033[0m#011gowaku.node2#011peermanager/peer_manager.go:194#011PeerManager init values#011{"maxConnections": 50, "maxRelayPeers": 40, "outRelayPeersTarget": 13, "inRelayPeersTarget": 27, "maxPeers": 250}
2024-05-21T07:30:09.277Z#011#033[34mINFO#033[0m#011gowaku.node2.relay#011relay/waku_relay.go:100#011relay config#011{"max-msg-size-bytes": 153600, "min-peers-to-publish": 0}
2024-05-21T07:30:09.277Z#011#033[34mINFO#033[0m#011gowaku.node2.connection-gater#011peermanager/connection_gater.go:32#011configured settings#011{"maxConnsPerIP": 5}
2024-05-21T07:30:09.278Z#011#033[33mWARN#033[0m#011p2p-config#011config/config.go:304#011rcmgr limit conflicts with connmgr limit: conn manager high watermark limit: 300, exceeds the system connection limit of: 1
2024-05-21T07:30:09.284Z#011#033[34mINFO#033[0m#011gowaku.node2.metadata#011metadata/waku_metadata.go:77#011metadata protocol started
```
Would be nice to disable the colors in logs which make everything almost unreadable.

**Comment by jakubgs** [comment]
The program is listening on two ports, no idea what those are for:
```
root@fc63821cdb22:/# netstat -lpnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:34527           0.0.0.0:*               LISTEN      1/storemsgcounter
tcp        0      0 127.0.0.11:41989        0.0.0.0:*               LISTEN      -
```

**Comment by richard-ramos** [comment]
In the latest commit I fixed the migration issue and added the following flags:  
- `--port` accepts an integer and if none specified, it will use a random port (which was the behaviour before the flag was added). 
- `--host`  uses `0.0.0.0`.

Regarding the listening ports, the port 34527 I'm sure is the random tcp port used by libp2p. The second one i have no idea. I tried on docker and couldnt find that port:
```
root@a3499514302f:/# netstat -lpntd
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:34125           0.0.0.0:*               LISTEN      1/storemsgcounter 
```

**Comment by richard-ramos** [comment]
> Would be nice to disable the colors in logs which make everything almost unreadable.

`--log-encoding=nocolor` fixes this

**Comment by jakubgs** [comment]
Changes:

- [`infra-misc#8495d3ca`](https://github.com/status-im/infra-misc/commit/8495d3ca) - telemetry: use new location of telemetry image
- [`infra-misc#544b48e5`](https://github.com/status-im/infra-misc/commit/544b48e5) - requirements: bump systemd-timer role
- [`infra-misc#843274df`](https://github.com/status-im/infra-misc/commit/843274df) - telemetry: move roles to separate playbook
- [`infra-misc#6960ea20`](https://github.com/status-im/infra-misc/commit/6960ea20) - telemetry: add storenode-messages-counter container

Also some to `telemetry` repo:

- [`telemetry#4d1a7f82`](https://github.com/status-im/telemetry/commit/4d1a7f82) - ci: use harbor.status.im to push docker images
- [`telemetry#7775d4b6`](https://github.com/status-im/telemetry/commit/7775d4b6) - ci: fix Docker build by using newer Go and Alpine

I consider this done:
```
jakubgs@node-01.he-eu-hel1.tmetry.misc:~ % docker ps
CONTAINER ID   NAMES               IMAGE                                                        CREATED         STATUS
f32739fe2ce0   telemetry-counter   harbor.status.im/wakuorg/storenode-messages-counter:deploy   3 minutes ago   Up 3 minutes
8c7f98313a44   telemetry-srv       harbor.status.im/wakuorg/telemetry:deploy                    7 hours ago     Up 7 hours
f8b3eba672ac   telemetry-db        postgres:13-alpine                                           7 hours ago     Up 7 hours
```
